apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kibana
  name: kibana-config
  labels:
    app: kibana
data:
  kibana.yml: |-
    server.host: 0.0.0.0
    elasticsearch:
      username: ${ELASTICSEARCH_USER}
      password: ${ELASTICSEARCH_PASSWORD}
    monitoring.ui.ccs.enabled: true