apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: es-auth-secret
  namespace: kibana
spec:
  backendType: gcpSecretsManager
  projectId: idfy-shared-prod
  data:
    - key: kibana-elasticsearch-auth-username
      name: elasticsearch-username
      version: 1
      isBinary: true
    - key: kibana-elasticsearch-auth-password
      name: elasticsearch-password
      version: 1
      isBinary: true
