apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: es-auth-secret
  namespace: kibana
spec:
  backendType: gcpSecretsManager
  projectId: idfy-shared-staging
  data:
    - key: es-cluster-auth-username
      name: es-cluster-username
      version: 2
      isBinary: true
    - key: es-cluster-auth-password
      name: es-cluster-password
      version: 2
      isBinary: true
    - key: es-cluster-service-account-token
      name: es-cluster-service-account-token
      version: 1
      isBinary: true