apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../bases
images:
- name: docker.elastic.co/kibana/kibana
  newTag: 8.6.0
resources:
 - kibana-auth-secret.yaml
patchesStrategicMerge:
  - patch.yaml
namespace: kibana
